name = "LibTIFF"
uuid = "09104962-a794-47fe-b6ff-83bb82a230bf"
authors = ["Mark Kittisopikul <markkitt@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Libtiff_jll = "89763e89-9b03-5906-acba-b20f662cd828"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
